{"name": "Получение ошибки при приеме заказа без id курьера", "status": "passed", "description": "Проверка принятия заказа без id курьера | POST /api/v1/courier/login", "start": 1716550350942, "stop": 1716550351379, "uuid": "6d711e71-d264-4c52-bd85-6bb384b99bb0", "historyId": "a2e6159059993b8f837ebbac869cb1d0", "testCaseId": "a2e6159059993b8f837ebbac869cb1d0", "fullName": "test_create_order.TestGetOrder#test_get_order_without_courier_id_failed", "labels": [{"name": "suite", "value": "test_create_order"}, {"name": "subSuite", "value": "TestGetOrder"}, {"name": "host", "value": "pc"}, {"name": "thread", "value": "11044-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_create_order"}]}