{"name": "Получение ошибки приема заказа без id заказа", "status": "passed", "description": "Проверка принятия заказа без id заказа | PUT /api/v1/orders/accept", "start": 1716550351660, "stop": 1716550352207, "uuid": "01f7d9aa-c105-4179-b1b4-d1614c4589cd", "historyId": "b6f9860c574d15c7aadef80b6e234ef6", "testCaseId": "b6f9860c574d15c7aadef80b6e234ef6", "fullName": "test_create_order.TestGetOrder#test_get_order_without_order_id_failed", "labels": [{"name": "suite", "value": "test_create_order"}, {"name": "subSuite", "value": "TestGetOrder"}, {"name": "host", "value": "pc"}, {"name": "thread", "value": "11044-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_create_order"}]}