{"name": "Получение ошибки при входе с некорректным паролем", "status": "passed", "description": "Проверка логина с некорректными данными | POST /api/v1/courier/login", "start": 1716550379268, "stop": 1716550379362, "uuid": "dbc12ad0-eedb-476f-b77e-a4ae8c18df3a", "historyId": "2dac8d80c24b83cd3f29c0599f4fcbaa", "testCaseId": "2dac8d80c24b83cd3f29c0599f4fcbaa", "fullName": "test_login_courier.TestAPICourierLogin#test_courier_login_wrong_password_failed", "labels": [{"name": "suite", "value": "test_login_courier"}, {"name": "subSuite", "value": "TestAPICourierLogin"}, {"name": "host", "value": "pc"}, {"name": "thread", "value": "8108-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_login_courier"}]}